# -*- coding: utf-8 -*-
"""for_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d0CQrz8rWdedUqXzFe-3xtzX70YZZt8Q
"""

print("Hello")